---
- name: Create and display "hello world version 1.0" on Amazon Linux
  hosts: all
  become: true
  gather_facts: false
  tasks:
    - name: Create file with 'hello world version 1.0 '
      ansible.builtin.copy:
        dest: /tmp/hello_world_version_1.0.txt
        content: "hello world version 1.0\n"
        owner: root
        mode: '0644'

    - name: Read file content
      ansible.builtin.command: cat /tmp/hello_world_version_1.0.txt
      register: file_output
      changed_when: false

    - name: Show file content
      ansible.builtin.debug:
        msg: "{{ file_output.stdout }}"


