name: Trigger AWX Job

on:
  push:
    branches:
      - new-branch

jobs:
  trigger-awx:
    runs-on: ubuntu-latest

    steps:
      - name: Launch AWX Job Template
        run: |
          curl -X POST "${{ secrets.AWX_URL }}/api/v2/job_templates/13/launch/" \
          -H "Authorization: Bearer ${{ secrets.AWX_TOKEN }}" \
          -H "Content-Type: application/json"
